// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/yuanhao/Desktop/change_avatar/my-app/node_modules/.pnpm/@umijs+renderer-react@4.4.11_nnrd3gsncyragczmpvfhocinkq/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/yuanhao/Desktop/change_avatar/my-app/node_modules/.pnpm/@umijs+renderer-react@4.4.11_nnrd3gsncyragczmpvfhocinkq/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/yuanhao/Desktop/change_avatar/my-app/node_modules/.pnpm/umi@4.4.11_enk4ejw6n42i3d5rmg7vwyr6le/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
